# Generated by Django 3.1.2 on 2022-10-06 02:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapp',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 6, 2, 8, 35, 276329, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapp',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapp',
            name='salary',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
