# Generated by Django 4.1.2 on 2022-10-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221005_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapp',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='jobapp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
