# Generated by Django 4.1.2 on 2022-10-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_jobapp_slug_alter_jobapp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapp',
            name='slug',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
    ]
