# Generated by Django 4.1.2 on 2022-10-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_jobapp_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapp',
            name='expiry',
            field=models.DateField(null=True),
        ),
    ]
